apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nodejs-endpoint
  name: nodejs-endpoint
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-endpoint
  template:
    metadata:
      labels:
        app: nodejs-endpoint
    spec:
      containers:
      - image: vkhazin/courseware-nodejs-container
        imagePullPolicy: Always
        name: nodejs-endpoint