apiVersion: "v1"
kind: "Service"
metadata:
  name: "nodejs-endpoint-service"
  namespace: "default"
  labels:
    app: "nodejs-endpoint"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 3001
  selector:
    app: "nodejs-endpoint"
  type: "LoadBalancer"
  loadBalancerIP: ""